plugins { id 'java-library' }
java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
tasks.register('regression', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'dev.minime.core.Regression'
    workingDir rootProject.projectDir
}
check.dependsOn regression
