# Applied identically to Android and the pinned desktop evaluator. The source
# archive stays untouched; only the generated translation unit changes.
function(minime_source_only target)
  file(SHA256 "${RIME}/src/rime/gear/script_translator.cc" digest)
  if(NOT digest STREQUAL "e743b15907bc8e15d8569e4e66f4361307b9a3daf7c2be619039883d3359c62b")
    message(FATAL_ERROR "Script translator differs from the reviewed librime 1.16.1 source")
  endif()
  file(READ "${RIME}/src/rime/gear/script_translator.cc" original)
  set(call "sentence_ = MakeSentence(dict, user_dict);")
  string(FIND "${original}" "${call}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Pinned script translator changed: review the assembly boundary")
  endif()
  string(REPLACE "${call}" "// MinIME: return stored phrases; never assemble a sentence." patched "${original}")
  set(output "${CMAKE_CURRENT_BINARY_DIR}/minime_script_translator.cc")
  file(WRITE "${output}" "${patched}")
  get_target_property(sources ${target} SOURCES)
  list(FILTER sources EXCLUDE REGEX "(^|/)script_translator\\.cc$")
  list(APPEND sources "${output}")
  set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
endfunction()
